@startuml devNest

package "Respositories"{
    component GamejamRepository 
    component TeamRepository 
    component VideogameRepository
    component UserRepository
    component CommentRepository
}

package "Services"{
    component gameJamService 
    component GameService 
    component RandomWordService
    component UserService
    component CommentService
    component AsyncEmailService
}

package "Controller"{
    component DevNestController 
    component GameController 
    component GameJamController
    component TeamController
    component UserController
}

gameJamService --> GamejamRepository
gameJamService --> TeamRepository 
gameJamService <-- DevNestController 

GameService --> VideogameRepository 
GameService <-- DevNestController

RandomWordService <-- DevNestController 

UserService --> UserRepository 
UserService --> TeamRepository  
UserService <-- DevNestController 

CommentService --> CommentRepository 
CommentService --> UserService 
CommentService --> gameJamService 
CommentService <-- DevNestController 


DevNestController --> UserService 
DevNestController --> gameJamService 
DevNestController --> RandomWordService 

GameController --> UserService 
GameController --> gameJamService 
GameController --> GameService 
GameController --> CommentService 

GameJamController --> UserService 
GameJamController --> gameJamService 
GameJamController --> RandomWordService 
GameJamController --> AsyncEmailService 

TeamController --> UserService 
TeamController --> gameJamService 

UserController --> UserService 
UserController --> AsyncEmailService 

@enduml