version: "3"

volumes:
  masterdata:
  slavedata:
  proxysqldata:

services:
  mysql-1:
    container_name: mysql-1
    build: ./mysqlMaster
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: devnest1234 
      MYSQL_DATABASE: devnest
    volumes:
      - masterdata:/var/lib/mysql
      - masterdata:/var/run/mysqld
      - masterdata:/var/log/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  mysql-2:
    container_name: mysql-2
    build: ./mysqlSlave
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: devnest1234 
      MYSQL_DATABASE: devnest
    volumes:
      - slavedata:/var/lib/mysql
      - slavedata:/var/run/mysqld
      - slavedata:/var/log/mysql
    depends_on:
      - mysql-1
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
  
  mysql-proxy:
    container_name: mysql-proxy
    build: ./proxysql
    restart: on-failure
    volumes:
      - proxysqldata:/var/lib/proxysql
    depends_on:
      - mysql-1
      - mysql-2
  
  internalService-1:
    container_name: internalService-1
    image: ghcr.io/darkops96/devnest-internalservice:latest
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-proxy:6033/devnest?serverTimezone=UTC
    depends_on:
      - mysql-proxy

  internalService-2:
    container_name: internalService-2
    image: ghcr.io/darkops96/devnest-internalservice:latest
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-proxy:6033/devnest?serverTimezone=UTC
    depends_on:
      - mysql-proxy

  internal-loadbalancer:
    container_name: internal-loadbalancer
    build: ./internalService_HAProxy
    restart: on-failure
    depends_on:
      - internalService-1
      - internalService-2

  devNest-1:
    container_name: devNest-1
    image: ghcr.io/darkops96/devnest-webapp:latest
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-proxy:6033/devnest?serverTimezone=UTC
      INTERNALSERVICE_BASEURI: http://internal-loadbalancer:80
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql-proxy
      - internal-loadbalancer

  devNest-2:
    container_name: devNest-2
    image: ghcr.io/darkops96/devnest-webapp:latest
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-proxy:6033/devnest?serverTimezone=UTC
      INTERNALSERVICE_BASEURI: http://internal-loadbalancer:80
    depends_on:
      - mysql-proxy
      - internal-loadbalancer

  webapp-loadbalancer:
    container_name: webapp-loadbalancer
    build: ./web_HAProxy    
    restart: on-failure
    ports:
      - 443:443
    depends_on:
      - devNest-1
      - devNest-2
