version: "3"

volumes:
  dbdata:

services:
  mysql:
    container_name: mysql
    image: mysql:latest    
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: devnest1234 
      MYSQL_DATABASE: devnest
      MYSQL_USER: devnest
      MYSQL_PASSWORD: devnest1234
    volumes:
      - dbdata:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
  
  internalService-1:
    container_name: internalService-1
    image: ghcr.io/darkops96/devnest-internalservice:latest
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devnest?serverTimezone=UTC
    depends_on:
      - mysql

  internalService-2:
    container_name: internalService-2
    image: ghcr.io/darkops96/devnest-internalservice:latest
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devnest?serverTimezone=UTC
    depends_on:
      - mysql

  internal-loadbalancer:
    container_name: internal-loadbalancer
    build: ./internalService_HAProxy
    restart: on-failure
    depends_on:
      - internalService-1
      - internalService-2

  devNest-1:
    container_name: devNest-1
    image: ghcr.io/darkops96/devnest-webapp:latest
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devnest?serverTimezone=UTC
      INTERNALSERVICE_BASEURI: http://internal-loadbalancer:80
    depends_on:
      - mysql
      - internal-loadbalancer

  devNest-2:
    container_name: devNest-2
    image: ghcr.io/darkops96/devnest-webapp:latest
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devnest?serverTimezone=UTC
      INTERNALSERVICE_BASEURI: http://internal-loadbalancer:80
    depends_on:
      - mysql
      - internal-loadbalancer

  webapp-loadbalancer:
    container_name: webapp-loadbalancer
    build: ./web_HAProxy    
    restart: on-failure
    ports:
      - 443:443
    depends_on:
      - devNest-1
      - devNest-2
