@startuml devNestInternalService

package "Respositories"{
    component VideogameRepository
}

package "Services"{
    component EmailService 
    component FileService
    component RandomWordService

}

package "Rest Controllers"{
    component EmailController 
    component FileController
    component RandomWordController
}

FileService --> VideogameRepository

RandomWordController --> RandomWordService
FileController --> FileService
EmailController --> EmailService

@enduml
