# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Manual Java CI with Maven (no Cache)

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    
    name: Dockerize
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3         
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Web App with Maven
      working-directory: ./devNest
      run: mvn compile jib:build -Djib.to.auth.username=${{ github.repository }} -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
    - name: Build Internal Service with Maven
      working-directory: ./devNestInternalService
      run: mvn compile jib:build -Djib.to.auth.username=${{ github.repository }} -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
